import "./WasteCollectionSection.css";
import wasteImg from "../../assets/ChatGPT Image Jan 2, 2026, 07_09_17 PM.png";

export default function WasteCollectionSection() {
  return (
    <>
      {/* TEXT SECTION */}
      <div className="container2 row" style={{ marginTop: "80px" }}>
         <div className="col-lg-7">
          <img src={wasteImg} alt="Waste Collection" />

        </div>
        <div className="col-lg-5">
        <p id="text1" className="fst-italic">
          <b>Waste collection</b> is the process of gathering, transporting, and
          disposing of waste materials generated by households, businesses,
          industries, and other sources. It is a crucial aspect of waste
          management aimed at maintaining public health, sanitation, and
          environmental protection.
          <br /><br />

          <b>Types of Waste</b>: Waste collection involves handling various types
          of waste, including municipal solid waste, recyclable materials,
          organic waste, hazardous waste, and construction debris.
          <br /><br />

          <b>Collection Methods</b>: Waste collection can be carried out through
          curbside collection, drop-off centers, and commercial waste services.
          <br /><br />

          <b>Collection Vehicles</b>: Specialized vehicles such as garbage
          trucks, compactors, recycling trucks, and roll-off trucks are used.
          <br /><br />

          <b>Frequency</b>: Collection frequency varies based on population
          density, waste type, and local regulations.
          <br /><br />

          <b>Segregation and Recycling</b>: Programs encourage segregation of
          waste at the source to support recycling and proper disposal.
          <br /><br />

          <b>Disposal and Treatment</b>: Waste is transported to landfills,
          recycling centers, composting facilities, or waste-to-energy plants.
          <br /><br />

          <b>Regulations and Compliance</b>: Waste collection follows local and
          national regulations to ensure environmental protection and public
          health.
          <br /><br />

          Overall, waste collection plays a critical role in sustainability and
          environmental conservation.

          <br /><br />

<b>Role of Technology in Waste Collection</b>:  
Modern waste collection systems increasingly rely on technology to improve
efficiency and accountability. GPS-enabled vehicles, digital tracking systems,
and mobile applications help monitor collection routes, timings, and waste
volumes, ensuring transparency and better service delivery.
<br /><br />

<b>Smart Segregation with QR-Based Identification</b>:  
In the Smart Garbage Reward System, each household or user is assigned a unique
QR code. During collection, waste collectors scan this QR code to identify the
user and verify whether waste has been properly segregated into biodegradable
and non-biodegradable categories.
<br /><br />

<b>Reward-Based Motivation</b>:  
Once segregation is verified, reward points are credited instantly to the
user’s account. These points act as an incentive mechanism, encouraging
consistent participation and responsible waste disposal habits among citizens.
<br /><br />

<b>Waste-to-Resource Conversion</b>:  
Biodegradable waste collected through proper segregation can be converted into
organic manure, compost, or biogas. This reduces landfill dependency and
supports sustainable agriculture and renewable energy generation.
<br /><br />

<b>Reduction of Environmental Pollution</b>:  
Efficient waste collection minimizes illegal dumping, reduces air and water
pollution, and prevents the spread of diseases. Proper handling of hazardous
and non-biodegradable waste further protects ecosystems and human health.
<br /><br />

<b>Economic and Social Impact</b>:  
A well-managed waste collection system lowers municipal costs, creates
employment opportunities, and promotes social responsibility. Citizens benefit
from cleaner surroundings, financial rewards, and improved quality of life.
<br /><br />

<b>Government Monitoring and Policy Support</b>:  
Data collected through the system enables authorities to monitor performance,
identify high-performing communities, and design targeted policies to improve
waste management infrastructure and awareness programs.
<br /><br />

<b>Long-Term Sustainability</b>:  
By combining systematic waste collection, segregation, recycling, and reward-
based incentives, the system fosters long-term behavioral change and builds a
culture of sustainability for future generations.

        </p>
        </div>
      </div>
    </>
  );
}
